version: "3.9"
services:
  project:
    image: alexxav/project:1.0.0
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
    - mongo-data:/data/db

volumes:
  mongo-data:
